package com.zoubei.mapper.cate;

import java.util.HashMap;

import com.zoubei.entity.cate.CateGroup;

public interface CateGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate_group
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    int deleteByPrimaryKey(Integer cgpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate_group
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    int insert(CateGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate_group
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    int insertSelective(CateGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate_group
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    CateGroup selectByPrimaryKey(Integer cgpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate_group
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    int updateByPrimaryKeySelective(CateGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate_group
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    int updateByPrimaryKey(CateGroup record);

    
    // 方法
	CateGroup selectCateGroupByNnamePasd(HashMap<String, Object> map);
}