package com.zoubei.mapper.cate;

import java.util.List;

import com.zoubei.entity.cate.Cate;
/**
 * 
 * @项目名称：maven_travel 美食店铺表Mapper接口
 *
 * @author ： YXM
 *
 * @date : 2018年4月19日 上午8:38:02
 */
public interface CateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    int deleteByPrimaryKey(Integer cateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    int insert(Cate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    int insertSelective(Cate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    Cate selectByPrimaryKey(Integer cateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    int updateByPrimaryKeySelective(Cate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_cate
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    int updateByPrimaryKey(Cate record);

    //根据景点区域id 查询该区域美食商家 排行优先推荐销量高的美食商家 order by
	List<Cate> selectCateBySceneAreaId(Integer areaId);

	//使用城市id获得美食商家
	List<Cate> selectCateList(Integer areaId);

	//每个美食所属店铺
	Cate selectCateByFoodsId(Integer foodId);

	// 获得所有的美食商家
	List<Cate> selectCateListAll();

	//商家管理员查询列表
	List<Cate> selectCateByGroup(Integer cgpId);

	//查询商家所有的店铺
	List<Cate> selectCateListAlls(Integer cgpId);
}