package com.zoubei.mapper.cate;

import com.zoubei.entity.cate.FoodsImg;

public interface FoodsImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods_img
     *
     * @mbggenerated Thu Apr 26 19:15:31 CST 2018
     */
    int insert(FoodsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods_img
     *
     * @mbggenerated Thu Apr 26 19:15:31 CST 2018
     */
    int insertSelective(FoodsImg record);
}