package com.zoubei.mapper.cate;

import java.util.List;
import java.util.Map;

import com.zoubei.entity.cate.Foods;

public interface FoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Sun Apr 15 15:05:14 CST 2018
     */
    int deleteByPrimaryKey(Integer foodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Sun Apr 15 15:05:14 CST 2018
     */
    int insert(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Sun Apr 15 15:05:14 CST 2018
     */
    int insertSelective(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Sun Apr 15 15:05:14 CST 2018
     */
    Foods selectByPrimaryKey(Integer foodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Sun Apr 15 15:05:14 CST 2018
     */
    int updateByPrimaryKeySelective(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Sun Apr 15 15:05:14 CST 2018
     */
    int updateByPrimaryKey(Foods record);

	List<Foods> selecCateFoodsList();

	//通过地区id动态获取美食列表
	List<Foods> selectFoodByAreaId(Map<String, Object> map);

	//添加美食返回主键
	void insertFood(Foods foods);

	//登录后商家看到的美食
	List<Foods> selectFoodByGroup(Integer cgpId);

	// 查询销量高的美食集合
	List<Foods> selecCateFoodsListOrder();

	//根据店铺ID查询相应的美食
	List<Foods> selectCateFoodByCateId(int cateId);
}