package com.zoubei.mapper.scene;
import java.util.HashMap;
import java.util.List;

import com.zoubei.entity.scene.Scene;
import com.zoubei.entity.tourist.Tourist;
/**
 * 
 * @项目名称：maven_travel  景点mapper层
 *
 * @author ： YXM
 *
 * @date : 2018年4月17日 下午2:20:00
 */
public interface SceneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    int deleteByPrimaryKey(Integer sceneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    int insert(Scene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    int insertSelective(Scene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    Scene selectByPrimaryKey(Integer sceneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    int updateByPrimaryKeySelective(Scene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    int updateByPrimaryKey(Scene record);

	Scene selectSceneById(Integer sceneId);

	List<Scene> selectSceneList();

	List<Scene> selectScene();

	/**
	 * 根据市级Pid来进行查询所有的区     继而查询出该市所有的景点
	 */
	List<Scene> selectSceneListByAreaId(Integer areaId);
	/**
	 * 根据区id   查询出该区所有的景点
	 */
	List<Scene> selectScenesByAreaId(Integer areaId);

	//景点排序 遍历order by 得到的 list 的集合
	List<Scene> selectSceneOrderBy(int sceneId);
	//后台查询所有图片的信息
	List<Tourist> selectSceneByimg();

	Scene selectSi();
	//查询游客信息生成图形报表
	List<Scene> selectShounum();

	//根据选择的ids进行导出相应的数据
	List<Scene> selectSceneByIds(HashMap<Object, Object> hashMap);


}