package com.zoubei.mapper.scene;

import java.util.HashMap;
import java.util.List;

import com.zoubei.entity.scene.SceneGroup;

public interface SceneGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_group
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    int deleteByPrimaryKey(Integer sgpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_group
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    int insert(SceneGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_group
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    int insertSelective(SceneGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_group
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    SceneGroup selectByPrimaryKey(Integer sgpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_group
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    int updateByPrimaryKeySelective(SceneGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_group
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    int updateByPrimaryKey(SceneGroup record);
    
    
    // 方法
	SceneGroup selectSceneGroupByNnamePasd(HashMap<String, Object> map);

	List<SceneGroup> selectSceneGroupList();

    
    
}