package com.zoubei.mapper.scene;

import java.util.List;

import com.zoubei.entity.scene.SceneImg;

public interface SceneImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_img
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_img
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    int insert(SceneImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_img
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    int insertSelective(SceneImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_img
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    SceneImg selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_img
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    int updateByPrimaryKeySelective(SceneImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_img
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    int updateByPrimaryKey(SceneImg record);

	List<SceneImg> selectSceneImgBySceneId(Integer sceneId);

	//通过订单支付中间的景点id获得景点的图片
	SceneImg selectSceneImgByTsoprSceneId(Integer sceneId);
}