package com.zoubei.mapper.scene;

import com.zoubei.entity.scene.SceneMap;
/**
 * 
 * @项目名称：maven_travel 景点坐标定位Mapper层
 *
 * @author ： YXM
 *
 * @date : 2018年4月19日 下午3:21:58
 */
public interface SceneMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_map
     *
     * @mbggenerated Thu Apr 19 14:54:46 CST 2018
     */
    int insert(SceneMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_map
     *
     * @mbggenerated Thu Apr 19 14:54:46 CST 2018
     */
    int insertSelective(SceneMap record);

	SceneMap selectSceneMapBySceneId(Integer sceneId);
}