package com.zoubei.mapper.scene;

import com.zoubei.entity.scene.SceneGroupRel;

public interface SceneGroupRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_group_rel
     *
     * @mbggenerated Sun Apr 15 14:53:00 CST 2018
     */
    int insert(SceneGroupRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_group_rel
     *
     * @mbggenerated Sun Apr 15 14:53:00 CST 2018
     */
    int insertSelective(SceneGroupRel record);
}