package com.zoubei.mapper.scene;

import java.util.List;

import com.zoubei.entity.scene.SceneType;

public interface SceneTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_type
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_type
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    int insert(SceneType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_type
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    int insertSelective(SceneType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_type
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    SceneType selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_type
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    int updateByPrimaryKeySelective(SceneType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_type
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    int updateByPrimaryKey(SceneType record);

	List<SceneType> selectSceneTypeList();
}