package com.zoubei.entity.scene;

public class AppImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_app_img.img_id
     *
     * @mbggenerated Sun Apr 15 15:09:08 CST 2018
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_app_img.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:09:08 CST 2018
     */
    private Integer appraiseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_app_img.img_url
     *
     * @mbggenerated Sun Apr 15 15:09:08 CST 2018
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_app_img.img_id
     *
     * @return the value of tra_app_img.img_id
     *
     * @mbggenerated Sun Apr 15 15:09:08 CST 2018
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_app_img.img_id
     *
     * @param imgId the value for tra_app_img.img_id
     *
     * @mbggenerated Sun Apr 15 15:09:08 CST 2018
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_app_img.appraise_id
     *
     * @return the value of tra_app_img.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:09:08 CST 2018
     */
    public Integer getAppraiseId() {
        return appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_app_img.appraise_id
     *
     * @param appraiseId the value for tra_app_img.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:09:08 CST 2018
     */
    public void setAppraiseId(Integer appraiseId) {
        this.appraiseId = appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_app_img.img_url
     *
     * @return the value of tra_app_img.img_url
     *
     * @mbggenerated Sun Apr 15 15:09:08 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_app_img.img_url
     *
     * @param imgUrl the value for tra_app_img.img_url
     *
     * @mbggenerated Sun Apr 15 15:09:08 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
}