package com.zoubei.entity.scene;

public class SceneType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_type.type_id
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_type.type_name
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_type.type_id
     *
     * @return the value of tra_scene_type.type_id
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_type.type_id
     *
     * @param typeId the value for tra_scene_type.type_id
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_type.type_name
     *
     * @return the value of tra_scene_type.type_name
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_type.type_name
     *
     * @param typeName the value for tra_scene_type.type_name
     *
     * @mbggenerated Sun Apr 15 14:53:20 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}