package com.zoubei.entity.scene;

import java.util.List;

public class Scene {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.scene_id
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private Integer sceneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.scene_name
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private String sceneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.area_id
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.scene_address
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private String sceneAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.scene_content
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private String sceneContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.scene_level
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private Integer sceneLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.scene_price
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private Integer scenePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.scene_nums
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private Integer sceneNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.scene_shounum
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private Integer sceneShounum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.scene_phone
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private String scenePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.scene_line
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private String sceneLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene.type_id
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    private Integer typeId;
    
    
    private String typeName;
    
    private List<SceneImg> scenceimgs;
    

    public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.scene_id
     *
     * @return the value of tra_scene.scene_id
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public Integer getSceneId() {
        return sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.scene_id
     *
     * @param sceneId the value for tra_scene.scene_id
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.scene_name
     *
     * @return the value of tra_scene.scene_name
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public String getSceneName() {
        return sceneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.scene_name
     *
     * @param sceneName the value for tra_scene.scene_name
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setSceneName(String sceneName) {
        this.sceneName = sceneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.area_id
     *
     * @return the value of tra_scene.area_id
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.area_id
     *
     * @param areaId the value for tra_scene.area_id
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.scene_address
     *
     * @return the value of tra_scene.scene_address
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public String getSceneAddress() {
        return sceneAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.scene_address
     *
     * @param sceneAddress the value for tra_scene.scene_address
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setSceneAddress(String sceneAddress) {
        this.sceneAddress = sceneAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.scene_content
     *
     * @return the value of tra_scene.scene_content
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public String getSceneContent() {
        return sceneContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.scene_content
     *
     * @param sceneContent the value for tra_scene.scene_content
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setSceneContent(String sceneContent) {
        this.sceneContent = sceneContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.scene_level
     *
     * @return the value of tra_scene.scene_level
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public Integer getSceneLevel() {
        return sceneLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.scene_level
     *
     * @param sceneLevel the value for tra_scene.scene_level
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setSceneLevel(Integer sceneLevel) {
        this.sceneLevel = sceneLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.scene_price
     *
     * @return the value of tra_scene.scene_price
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public Integer getScenePrice() {
        return scenePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.scene_price
     *
     * @param scenePrice the value for tra_scene.scene_price
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setScenePrice(Integer scenePrice) {
        this.scenePrice = scenePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.scene_nums
     *
     * @return the value of tra_scene.scene_nums
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public Integer getSceneNums() {
        return sceneNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.scene_nums
     *
     * @param sceneNums the value for tra_scene.scene_nums
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setSceneNums(Integer sceneNums) {
        this.sceneNums = sceneNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.scene_shounum
     *
     * @return the value of tra_scene.scene_shounum
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public Integer getSceneShounum() {
        return sceneShounum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.scene_shounum
     *
     * @param sceneShounum the value for tra_scene.scene_shounum
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setSceneShounum(Integer sceneShounum) {
        this.sceneShounum = sceneShounum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.scene_phone
     *
     * @return the value of tra_scene.scene_phone
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public String getScenePhone() {
        return scenePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.scene_phone
     *
     * @param scenePhone the value for tra_scene.scene_phone
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setScenePhone(String scenePhone) {
        this.scenePhone = scenePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.scene_line
     *
     * @return the value of tra_scene.scene_line
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public String getSceneLine() {
        return sceneLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.scene_line
     *
     * @param sceneLine the value for tra_scene.scene_line
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setSceneLine(String sceneLine) {
        this.sceneLine = sceneLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene.type_id
     *
     * @return the value of tra_scene.type_id
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene.type_id
     *
     * @param typeId the value for tra_scene.type_id
     *
     * @mbggenerated Sun Apr 15 14:53:38 CST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
    
    // 新添加属性
    private List<SceneImg> listSceneImg;

	public List<SceneImg> getListSceneImg() {
		return listSceneImg;
	}

	public void setListSceneImg(List<SceneImg> listSceneImg) {
		this.listSceneImg = listSceneImg;
	}

	public List<SceneImg> getScenceimgs() {
		return scenceimgs;
	}

	public void setScenceimgs(List<SceneImg> scenceimgs) {
		this.scenceimgs = scenceimgs;
	}
	
}