package com.zoubei.entity.scene;

public class SceneGroupRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_group_rel.sgp_id
     *
     * @mbggenerated Sun Apr 15 14:53:00 CST 2018
     */
    private Integer sgpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_group_rel.scene_id
     *
     * @mbggenerated Sun Apr 15 14:53:00 CST 2018
     */
    private Integer sceneId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_group_rel.sgp_id
     *
     * @return the value of tra_scene_group_rel.sgp_id
     *
     * @mbggenerated Sun Apr 15 14:53:00 CST 2018
     */
    public Integer getSgpId() {
        return sgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_group_rel.sgp_id
     *
     * @param sgpId the value for tra_scene_group_rel.sgp_id
     *
     * @mbggenerated Sun Apr 15 14:53:00 CST 2018
     */
    public void setSgpId(Integer sgpId) {
        this.sgpId = sgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_group_rel.scene_id
     *
     * @return the value of tra_scene_group_rel.scene_id
     *
     * @mbggenerated Sun Apr 15 14:53:00 CST 2018
     */
    public Integer getSceneId() {
        return sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_group_rel.scene_id
     *
     * @param sceneId the value for tra_scene_group_rel.scene_id
     *
     * @mbggenerated Sun Apr 15 14:53:00 CST 2018
     */
    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }
}