package com.zoubei.entity.scene;
/**
 * 
 * @项目名称：maven_travel  景点坐标定位表
 *
 * @author ： YXM
 *
 * @date : 2018年4月19日 下午3:20:08
 */
public class SceneMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_map.scene_id
     *
     * @mbggenerated Thu Apr 19 14:54:46 CST 2018
     */
    private Integer sceneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_map.mapx
     *
     * @mbggenerated Thu Apr 19 14:54:46 CST 2018
     */
    private String mapx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_map.mapy
     *
     * @mbggenerated Thu Apr 19 14:54:46 CST 2018
     */
    private String mapy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_map.scene_id
     *
     * @return the value of tra_scene_map.scene_id
     *
     * @mbggenerated Thu Apr 19 14:54:46 CST 2018
     */
    public Integer getSceneId() {
        return sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_map.scene_id
     *
     * @param sceneId the value for tra_scene_map.scene_id
     *
     * @mbggenerated Thu Apr 19 14:54:46 CST 2018
     */
    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_map.mapx
     *
     * @return the value of tra_scene_map.mapx
     *
     * @mbggenerated Thu Apr 19 14:54:46 CST 2018
     */
    public String getMapx() {
        return mapx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_map.mapx
     *
     * @param mapx the value for tra_scene_map.mapx
     *
     * @mbggenerated Thu Apr 19 14:54:46 CST 2018
     */
    public void setMapx(String mapx) {
        this.mapx = mapx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_map.mapy
     *
     * @return the value of tra_scene_map.mapy
     *
     * @mbggenerated Thu Apr 19 14:54:46 CST 2018
     */
    public String getMapy() {
        return mapy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_map.mapy
     *
     * @param mapy the value for tra_scene_map.mapy
     *
     * @mbggenerated Thu Apr 19 14:54:46 CST 2018
     */
    public void setMapy(String mapy) {
        this.mapy = mapy;
    }
}