package com.zoubei.entity.scene;

public class SceneGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_group.sgp_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    private Integer sgpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_group.sgp_nickname
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    private String sgpNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_group.sgp_password
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    private String sgpPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_group.sgp_unitname
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    private String sgpUnitname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_group.sgp_address
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    private String sgpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_group.jur_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    private Integer jurId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_group.status_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_group.area_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    private Integer areaId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_group.sgp_id
     *
     * @return the value of tra_scene_group.sgp_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public Integer getSgpId() {
        return sgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_group.sgp_id
     *
     * @param sgpId the value for tra_scene_group.sgp_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public void setSgpId(Integer sgpId) {
        this.sgpId = sgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_group.sgp_nickname
     *
     * @return the value of tra_scene_group.sgp_nickname
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public String getSgpNickname() {
        return sgpNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_group.sgp_nickname
     *
     * @param sgpNickname the value for tra_scene_group.sgp_nickname
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public void setSgpNickname(String sgpNickname) {
        this.sgpNickname = sgpNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_group.sgp_password
     *
     * @return the value of tra_scene_group.sgp_password
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public String getSgpPassword() {
        return sgpPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_group.sgp_password
     *
     * @param sgpPassword the value for tra_scene_group.sgp_password
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public void setSgpPassword(String sgpPassword) {
        this.sgpPassword = sgpPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_group.sgp_unitname
     *
     * @return the value of tra_scene_group.sgp_unitname
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public String getSgpUnitname() {
        return sgpUnitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_group.sgp_unitname
     *
     * @param sgpUnitname the value for tra_scene_group.sgp_unitname
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public void setSgpUnitname(String sgpUnitname) {
        this.sgpUnitname = sgpUnitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_group.sgp_address
     *
     * @return the value of tra_scene_group.sgp_address
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public String getSgpAddress() {
        return sgpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_group.sgp_address
     *
     * @param sgpAddress the value for tra_scene_group.sgp_address
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public void setSgpAddress(String sgpAddress) {
        this.sgpAddress = sgpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_group.jur_id
     *
     * @return the value of tra_scene_group.jur_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public Integer getJurId() {
        return jurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_group.jur_id
     *
     * @param jurId the value for tra_scene_group.jur_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public void setJurId(Integer jurId) {
        this.jurId = jurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_group.status_id
     *
     * @return the value of tra_scene_group.status_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_group.status_id
     *
     * @param statusId the value for tra_scene_group.status_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_group.area_id
     *
     * @return the value of tra_scene_group.area_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_group.area_id
     *
     * @param areaId the value for tra_scene_group.area_id
     *
     * @mbggenerated Thu Apr 19 10:41:50 CST 2018
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }
}