package com.zoubei.entity.scene;

import java.util.List;

public class SceneImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_img.img_id
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_img.scene_id
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    private Integer sceneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_img.img_url
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_img.img_id
     *
     * @return the value of tra_scene_img.img_id
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_img.img_id
     *
     * @param imgId the value for tra_scene_img.img_id
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_img.scene_id
     *
     * @return the value of tra_scene_img.scene_id
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    public Integer getSceneId() {
        return sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_img.scene_id
     *
     * @param sceneId the value for tra_scene_img.scene_id
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_img.img_url
     *
     * @return the value of tra_scene_img.img_url
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_img.img_url
     *
     * @param imgUrl the value for tra_scene_img.img_url
     *
     * @mbggenerated Tue Apr 17 14:07:36 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

}