package com.zoubei.mapper.tourist;

import java.util.List;

import com.zoubei.entity.tourist.TouristSceneOrderRel;

public interface TouristSceneOrderRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_order_rel
     *
     * @mbggenerated Sun Apr 15 15:06:34 CST 2018
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_order_rel
     *
     * @mbggenerated Sun Apr 15 15:06:34 CST 2018
     */
    int insert(TouristSceneOrderRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_order_rel
     *
     * @mbggenerated Sun Apr 15 15:06:34 CST 2018
     */
    int insertSelective(TouristSceneOrderRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_order_rel
     *
     * @mbggenerated Sun Apr 15 15:06:34 CST 2018
     */
    TouristSceneOrderRel selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_order_rel
     *
     * @mbggenerated Sun Apr 15 15:06:34 CST 2018
     */
    int updateByPrimaryKeySelective(TouristSceneOrderRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_order_rel
     *
     * @mbggenerated Sun Apr 15 15:06:34 CST 2018
     */
    int updateByPrimaryKey(TouristSceneOrderRel record);

    //获得所有景点的订单   关联景点游客
	List<TouristSceneOrderRel> selectOrderBySceneList();

	// 景点商家 -- 登录查询自己的景点关联订单信息 通过商家id
	List<TouristSceneOrderRel> selectOrderByGroupSceneList(Integer sgpId);
}