package com.zoubei.mapper.tourist;

import com.zoubei.entity.tourist.TouristAwardRel;

public interface TouristAwardRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_award
     *
     * @mbggenerated Sun Apr 15 14:50:28 CST 2018
     */
    int insert(TouristAwardRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_award
     *
     * @mbggenerated Sun Apr 15 14:50:28 CST 2018
     */
    int insertSelective(TouristAwardRel record);
}