package com.zoubei.mapper.tourist;

import java.util.List;

import com.zoubei.entity.tourist.TouristSceneAppraise;

public interface TouristSceneAppraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_appraise
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    int deleteByPrimaryKey(Integer appraiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_appraise
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    int insert(TouristSceneAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_appraise
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    int insertSelective(TouristSceneAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_appraise
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    TouristSceneAppraise selectByPrimaryKey(Integer appraiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_appraise
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    int updateByPrimaryKeySelective(TouristSceneAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_scene_appraise
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    int updateByPrimaryKey(TouristSceneAppraise record);

    //通过游客id获得游客评论
	List<TouristSceneAppraise> selectTouristAppraise(Integer touristId);

	//获得景点评论记录条数通过景点id
	Integer selectSceneAppraiseRecord(Integer sceneId);

	
}