package com.zoubei.mapper.tourist;

import java.util.List;

import com.zoubei.entity.tourist.TouristCatelRel;

public interface TouristCatelRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_rel
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_rel
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    int insert(TouristCatelRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_rel
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    int insertSelective(TouristCatelRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_rel
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    TouristCatelRel selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_rel
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    int updateByPrimaryKeySelective(TouristCatelRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_rel
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    int updateByPrimaryKey(TouristCatelRel record);

    //美食订单管理列表展示
	List<TouristCatelRel> selectOrderByFoodList();

	//美食商家登录  -- 查询订单美食 关联用户
	List<TouristCatelRel> selectOrderByGroupFoodList(Integer cgpId);
}