package com.zoubei.mapper.tourist;

import java.util.List;

import com.zoubei.entity.tourist.Tourist;
/**
 * 
 * @项目名称：maven_travel 游客Mpper层
 *
 * @author ： YXM
 *
 * @date : 2018年4月17日 下午1:28:28
 */
public interface TouristMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist
     *
     * @mbggenerated Sun Apr 15 11:14:47 CST 2018
     */
    int deleteByPrimaryKey(Integer touristId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist
     *
     * @mbggenerated Sun Apr 15 11:14:47 CST 2018
     */
    int insert(Tourist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist
     *
     * @mbggenerated Sun Apr 15 11:14:47 CST 2018
     */
    int insertSelective(Tourist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist
     *
     * @mbggenerated Sun Apr 15 11:14:47 CST 2018
     */
    Tourist selectByPrimaryKey(Integer touristId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist
     *
     * @mbggenerated Sun Apr 15 11:14:47 CST 2018
     */
    int updateByPrimaryKeySelective(Tourist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist
     *
     * @mbggenerated Sun Apr 15 11:14:47 CST 2018
     */
    int updateByPrimaryKey(Tourist record);
    
	Tourist selectTourist(String touristNickname);
	
	void insertRegister(Tourist tourist);

	//查询游客信息
	Tourist selectToutistList(Integer touristId);
	//修改个人中心个人信息
	void updateTour(Tourist tourist);
	//修改个人中心图片
	void updateTuPian(Tourist tourist);
	//按id查询景点表
	Tourist selectTouristListById(Integer touristId);
	//后台查询游客所有信息
	List<Tourist> selectTouristByList();
	
	Tourist toUpdateTourist(Integer touristId);

	

	

}