package com.zoubei.mapper.tourist;

import com.zoubei.entity.tourist.TouristCatelCollecRel;

public interface TouristCatelCollecRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_cate_collec_rel
     *
     * @mbggenerated Sun Apr 15 15:17:19 CST 2018
     */
    int insert(TouristCatelCollecRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_cate_collec_rel
     *
     * @mbggenerated Sun Apr 15 15:17:19 CST 2018
     */
    int insertSelective(TouristCatelCollecRel record);
}