package com.zoubei.mapper.tourist;

import java.util.List;

import com.zoubei.entity.tourist.TouristSceneOrderPriceRel;
/**
 * 
 * @项目名称：maven_travel 景点订单支付表
 *
 * @author ： YXM
 *
 * @date : 2018年4月26日 下午6:39:27
 */
public interface TouristSceneOrderPriceRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_scene_orderprice_rel
     *
     * @mbggenerated Thu Apr 26 18:37:49 CST 2018
     */
    int deleteByPrimaryKey(Integer touristOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_scene_orderprice_rel
     *
     * @mbggenerated Thu Apr 26 18:37:49 CST 2018
     */
    int insert(TouristSceneOrderPriceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_scene_orderprice_rel
     *
     * @mbggenerated Thu Apr 26 18:37:49 CST 2018
     */
    int insertSelective(TouristSceneOrderPriceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_scene_orderprice_rel
     *
     * @mbggenerated Thu Apr 26 18:37:49 CST 2018
     */
    TouristSceneOrderPriceRel selectByPrimaryKey(Integer touristOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_scene_orderprice_rel
     *
     * @mbggenerated Thu Apr 26 18:37:49 CST 2018
     */
    int updateByPrimaryKeySelective(TouristSceneOrderPriceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_scene_orderprice_rel
     *
     * @mbggenerated Thu Apr 26 18:37:49 CST 2018
     */
    int updateByPrimaryKey(TouristSceneOrderPriceRel record);

    //获得待支付订单查询到的数据集合
	List<TouristSceneOrderPriceRel> selectTsoprByTouristId(Integer touristId);

	//根据订单id获得支付信息  总价  产品名称 等
	TouristSceneOrderPriceRel selectSceneOrderPayByOrderId(Integer orderId);

	//修改支付订单状态
	void updateTouristPayInfo(TouristSceneOrderPriceRel tsopr);
}