package com.zoubei.mapper.tourist;

import java.util.List;

import com.zoubei.entity.tourist.TouristCatelEvaluateRel;

public interface TouristCatelEvaluateRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_evaluate
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    int deleteByPrimaryKey(Integer appraiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_evaluate
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    int insert(TouristCatelEvaluateRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_evaluate
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    int insertSelective(TouristCatelEvaluateRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_evaluate
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    TouristCatelEvaluateRel selectByPrimaryKey(Integer appraiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_evaluate
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    int updateByPrimaryKeySelective(TouristCatelEvaluateRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_touris_catel_evaluate
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    int updateByPrimaryKey(TouristCatelEvaluateRel record);

    //查询评价表  关联订单 和 食物 和订单 店铺名称 通过用户id查询
	List<TouristCatelEvaluateRel> selectCatelEvaluateByTouristId(
			Integer touristId);
}