package com.zoubei.mapper.tourist;

import com.zoubei.entity.tourist.TouristHotelCollecRel;

public interface TouristHotelCollecRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_hotel_collec_rel
     *
     * @mbggenerated Sun Apr 15 15:18:40 CST 2018
     */
    int insert(TouristHotelCollecRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_hotel_collec_rel
     *
     * @mbggenerated Sun Apr 15 15:18:40 CST 2018
     */
    int insertSelective(TouristHotelCollecRel record);
}