package com.zoubei.mapper.tourist;

import java.util.List;

import com.zoubei.entity.tourist.TouristHotelRel;

public interface TouristHotelRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_hotel_rel
     *
     * @mbggenerated Sun Apr 15 15:18:03 CST 2018
     */
    int deleteByPrimaryKey(Integer thrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_hotel_rel
     *
     * @mbggenerated Sun Apr 15 15:18:03 CST 2018
     */
    int insert(TouristHotelRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_hotel_rel
     *
     * @mbggenerated Sun Apr 15 15:18:03 CST 2018
     */
    int insertSelective(TouristHotelRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_hotel_rel
     *
     * @mbggenerated Sun Apr 15 15:18:03 CST 2018
     */
    TouristHotelRel selectByPrimaryKey(Integer thrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_hotel_rel
     *
     * @mbggenerated Sun Apr 15 15:18:03 CST 2018
     */
    int updateByPrimaryKeySelective(TouristHotelRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_tourist_hotel_rel
     *
     * @mbggenerated Sun Apr 15 15:18:03 CST 2018
     */
    int updateByPrimaryKey(TouristHotelRel record);

    //酒店订单管理列表展示
	List<TouristHotelRel> selectOrderByHotelList();

	//酒店商家登录查看自己酒店订单
	List<TouristHotelRel> selectOrderByGroupHotelList(Integer hgpId);
}