package com.zoubei.entity.hotel;

public class HotelGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_group.hgp_id
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    private Integer hgpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_group.hgp_nickname
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    private String hgpNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_group.hgp_password
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    private String hgpPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_group.hgp_realname
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    private String hgpRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_group.jur_id
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    private Integer jurId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_group.status_id
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    private Integer statusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_group.hgp_id
     *
     * @return the value of tra_hotel_group.hgp_id
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public Integer getHgpId() {
        return hgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_group.hgp_id
     *
     * @param hgpId the value for tra_hotel_group.hgp_id
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public void setHgpId(Integer hgpId) {
        this.hgpId = hgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_group.hgp_nickname
     *
     * @return the value of tra_hotel_group.hgp_nickname
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public String getHgpNickname() {
        return hgpNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_group.hgp_nickname
     *
     * @param hgpNickname the value for tra_hotel_group.hgp_nickname
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public void setHgpNickname(String hgpNickname) {
        this.hgpNickname = hgpNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_group.hgp_password
     *
     * @return the value of tra_hotel_group.hgp_password
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public String getHgpPassword() {
        return hgpPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_group.hgp_password
     *
     * @param hgpPassword the value for tra_hotel_group.hgp_password
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public void setHgpPassword(String hgpPassword) {
        this.hgpPassword = hgpPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_group.hgp_realname
     *
     * @return the value of tra_hotel_group.hgp_realname
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public String getHgpRealname() {
        return hgpRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_group.hgp_realname
     *
     * @param hgpRealname the value for tra_hotel_group.hgp_realname
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public void setHgpRealname(String hgpRealname) {
        this.hgpRealname = hgpRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_group.jur_id
     *
     * @return the value of tra_hotel_group.jur_id
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public Integer getJurId() {
        return jurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_group.jur_id
     *
     * @param jurId the value for tra_hotel_group.jur_id
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public void setJurId(Integer jurId) {
        this.jurId = jurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_group.status_id
     *
     * @return the value of tra_hotel_group.status_id
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_group.status_id
     *
     * @param statusId the value for tra_hotel_group.status_id
     *
     * @mbggenerated Sun Apr 15 15:09:56 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
}