package com.zoubei.entity.hotel;

public class HotelPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_price.price_id
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    private Integer priceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_price.price_price
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    private Integer pricePrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_price.price_id
     *
     * @return the value of tra_hotel_price.price_id
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    public Integer getPriceId() {
        return priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_price.price_id
     *
     * @param priceId the value for tra_hotel_price.price_id
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    public void setPriceId(Integer priceId) {
        this.priceId = priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_price.price_price
     *
     * @return the value of tra_hotel_price.price_price
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    public Integer getPricePrice() {
        return pricePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_price.price_price
     *
     * @param pricePrice the value for tra_hotel_price.price_price
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    public void setPricePrice(Integer pricePrice) {
        this.pricePrice = pricePrice;
    }
}