package com.zoubei.entity.hotel;

public class HotelGroupRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_group_rel.hgp_id
     *
     * @mbggenerated Sun Apr 15 15:10:19 CST 2018
     */
    private Integer hgpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_group_rel.hotel_id
     *
     * @mbggenerated Sun Apr 15 15:10:19 CST 2018
     */
    private Integer hotelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_group_rel.hgp_id
     *
     * @return the value of tra_hotel_group_rel.hgp_id
     *
     * @mbggenerated Sun Apr 15 15:10:19 CST 2018
     */
    public Integer getHgpId() {
        return hgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_group_rel.hgp_id
     *
     * @param hgpId the value for tra_hotel_group_rel.hgp_id
     *
     * @mbggenerated Sun Apr 15 15:10:19 CST 2018
     */
    public void setHgpId(Integer hgpId) {
        this.hgpId = hgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_group_rel.hotel_id
     *
     * @return the value of tra_hotel_group_rel.hotel_id
     *
     * @mbggenerated Sun Apr 15 15:10:19 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_group_rel.hotel_id
     *
     * @param hotelId the value for tra_hotel_group_rel.hotel_id
     *
     * @mbggenerated Sun Apr 15 15:10:19 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }
}