package com.zoubei.entity.hotel;

public class HotelPriceRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_price_rel.hpr_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    private Integer hprId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_price_rel.price_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    private Integer priceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_price_rel.typei_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    private Integer typeiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_price_rel.hotel_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    private Integer hotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel_price_rel.status_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    private Integer statusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_price_rel.hpr_id
     *
     * @return the value of tra_hotel_price_rel.hpr_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    public Integer getHprId() {
        return hprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_price_rel.hpr_id
     *
     * @param hprId the value for tra_hotel_price_rel.hpr_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    public void setHprId(Integer hprId) {
        this.hprId = hprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_price_rel.price_id
     *
     * @return the value of tra_hotel_price_rel.price_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    public Integer getPriceId() {
        return priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_price_rel.price_id
     *
     * @param priceId the value for tra_hotel_price_rel.price_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    public void setPriceId(Integer priceId) {
        this.priceId = priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_price_rel.typei_id
     *
     * @return the value of tra_hotel_price_rel.typei_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    public Integer getTypeiId() {
        return typeiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_price_rel.typei_id
     *
     * @param typeiId the value for tra_hotel_price_rel.typei_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    public void setTypeiId(Integer typeiId) {
        this.typeiId = typeiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_price_rel.hotel_id
     *
     * @return the value of tra_hotel_price_rel.hotel_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_price_rel.hotel_id
     *
     * @param hotelId the value for tra_hotel_price_rel.hotel_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel_price_rel.status_id
     *
     * @return the value of tra_hotel_price_rel.status_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel_price_rel.status_id
     *
     * @param statusId the value for tra_hotel_price_rel.status_id
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
}