package com.zoubei.entity.hotel;

public class Hotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel.hotel_id
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    private Integer hotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel.hotel_hotelname
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    private String hotelHotelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel.area_id
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel.hotel_adress
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    private String hotelAdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel.level_id
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    private Integer levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel.hotel_num
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    private Integer hotelNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel.hotel_message
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    private String hotelMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel.hotel_phone
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    private String hotelPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_hotel.hotel_logo
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    private String hotelLogo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel.hotel_id
     *
     * @return the value of tra_hotel.hotel_id
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel.hotel_id
     *
     * @param hotelId the value for tra_hotel.hotel_id
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel.hotel_hotelname
     *
     * @return the value of tra_hotel.hotel_hotelname
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public String getHotelHotelname() {
        return hotelHotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel.hotel_hotelname
     *
     * @param hotelHotelname the value for tra_hotel.hotel_hotelname
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public void setHotelHotelname(String hotelHotelname) {
        this.hotelHotelname = hotelHotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel.area_id
     *
     * @return the value of tra_hotel.area_id
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel.area_id
     *
     * @param areaId the value for tra_hotel.area_id
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel.hotel_adress
     *
     * @return the value of tra_hotel.hotel_adress
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public String getHotelAdress() {
        return hotelAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel.hotel_adress
     *
     * @param hotelAdress the value for tra_hotel.hotel_adress
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public void setHotelAdress(String hotelAdress) {
        this.hotelAdress = hotelAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel.level_id
     *
     * @return the value of tra_hotel.level_id
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel.level_id
     *
     * @param levelId the value for tra_hotel.level_id
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel.hotel_num
     *
     * @return the value of tra_hotel.hotel_num
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public Integer getHotelNum() {
        return hotelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel.hotel_num
     *
     * @param hotelNum the value for tra_hotel.hotel_num
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public void setHotelNum(Integer hotelNum) {
        this.hotelNum = hotelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel.hotel_message
     *
     * @return the value of tra_hotel.hotel_message
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public String getHotelMessage() {
        return hotelMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel.hotel_message
     *
     * @param hotelMessage the value for tra_hotel.hotel_message
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public void setHotelMessage(String hotelMessage) {
        this.hotelMessage = hotelMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel.hotel_phone
     *
     * @return the value of tra_hotel.hotel_phone
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public String getHotelPhone() {
        return hotelPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel.hotel_phone
     *
     * @param hotelPhone the value for tra_hotel.hotel_phone
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public void setHotelPhone(String hotelPhone) {
        this.hotelPhone = hotelPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_hotel.hotel_logo
     *
     * @return the value of tra_hotel.hotel_logo
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public String getHotelLogo() {
        return hotelLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_hotel.hotel_logo
     *
     * @param hotelLogo the value for tra_hotel.hotel_logo
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    public void setHotelLogo(String hotelLogo) {
        this.hotelLogo = hotelLogo;
    }
}