package com.zoubei.entity.hotel;

public class HotelType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_type.typei_id
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    private Integer typeiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_type.type_name
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_type.typei_id
     *
     * @return the value of tra_type.typei_id
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    public Integer getTypeiId() {
        return typeiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_type.typei_id
     *
     * @param typeiId the value for tra_type.typei_id
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    public void setTypeiId(Integer typeiId) {
        this.typeiId = typeiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_type.type_name
     *
     * @return the value of tra_type.type_name
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_type.type_name
     *
     * @param typeName the value for tra_type.type_name
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}