package com.zoubei.mapper.other;

import java.util.List;
import java.util.Map;

import com.zoubei.entity.other.Area;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_area
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    int deleteByPrimaryKey(Integer areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_area
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_area
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_area
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    Area selectByPrimaryKey(Integer areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_area
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_area
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    int updateByPrimaryKey(Area record);

	Area selectAreaBySceneId(Integer sceneId);

	List<Area> selectAreaList();

	List<Area> selectAreaListBySgpId(Integer sgpid);


	void insertAreaInfo(Area area);

	//所有的市 区
	List<Area> selectAreaShiQuList(Integer pid);

	//删除城市 + 地址
	Integer deleteAreaInfoByareaId(Integer areaId);
	//查询酒店所属区域 通过ID
	List<Area> selectAreaByHotelId(Integer areaId);

	/**
	 * 获得酒店地址 通过酒店地址id
	 */
	Area selectHotelAreaByAreaId(Integer areaId);

	//通过酒店地址Id查询地址表信息
	Area selectAreaByHotelAreaId(Integer areaId);

	//动态回显美食下拉地址
	Area selectFoodByAreaEcho(Map<String, Object> map);

	//获得地区美食地址 通过店铺id
	Area selectAreaByFoodId(Integer cateId);



}