package com.zoubei.mapper.other;

import com.zoubei.entity.other.Jurisdict;

public interface JurisdictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_jurisdict
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    int deleteByPrimaryKey(Integer jurId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_jurisdict
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    int insert(Jurisdict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_jurisdict
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    int insertSelective(Jurisdict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_jurisdict
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    Jurisdict selectByPrimaryKey(Integer jurId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_jurisdict
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    int updateByPrimaryKeySelective(Jurisdict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_jurisdict
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    int updateByPrimaryKey(Jurisdict record);
}