package com.zoubei.mapper.other;

import com.zoubei.entity.other.JurUrlRel;

public interface JurUrlRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_jur_url_rel
     *
     * @mbggenerated Sun Apr 15 15:20:10 CST 2018
     */
    int insert(JurUrlRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_jur_url_rel
     *
     * @mbggenerated Sun Apr 15 15:20:10 CST 2018
     */
    int insertSelective(JurUrlRel record);
}