package com.zoubei.mapper.other;

import java.util.HashMap;

import com.zoubei.entity.other.SuperManager;

public interface SuperManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_supermanager
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    int deleteByPrimaryKey(Integer supId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_supermanager
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    int insert(SuperManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_supermanager
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    int insertSelective(SuperManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_supermanager
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    SuperManager selectByPrimaryKey(Integer supId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_supermanager
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    int updateByPrimaryKeySelective(SuperManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_supermanager
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    int updateByPrimaryKey(SuperManager record);

    
    // 方法 
	SuperManager selectSuperManagerByNnamePasd(HashMap<String, Object> map);
}