package com.zoubei.mapper.other;

import com.zoubei.entity.other.Url;

public interface UrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_url
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    int deleteByPrimaryKey(Integer urlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_url
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    int insert(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_url
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    int insertSelective(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_url
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    Url selectByPrimaryKey(Integer urlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_url
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    int updateByPrimaryKeySelective(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_url
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    int updateByPrimaryKey(Url record);
}