package com.zoubei.entity.other;

import java.util.List;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_area.area_id
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_area.area_name
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    private String areaName;
    
    //地址集合
    private String areaListName ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_area.area_pid
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    private Integer areaPid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_area.area_id
     *
     * @return the value of tra_area.area_id
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_area.area_id
     *
     * @param areaId the value for tra_area.area_id
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_area.area_name
     *
     * @return the value of tra_area.area_name
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_area.area_name
     *
     * @param areaName the value for tra_area.area_name
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_area.area_pid
     *
     * @return the value of tra_area.area_pid
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    public Integer getAreaPid() {
        return areaPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_area.area_pid
     *
     * @param areaPid the value for tra_area.area_pid
     *
     * @mbggenerated Mon Apr 16 15:39:55 CST 2018
     */
    public void setAreaPid(Integer areaPid) {
        this.areaPid = areaPid;
    }


	public String getAreaListName() {
		return areaListName;
	}

	public void setAreaListName(String areaListName) {
		this.areaListName = areaListName;
	}
    
    
    // 市对应的去对象
    private List<Area> areas;

	public List<Area> getAreas() {
		return areas;
	}

	public void setAreas(List<Area> areas) {
		this.areas = areas;
	}

	@Override
	public String toString() {
		return "Area [areaId=" + areaId + ", areaName=" + areaName
				+ ", areaPid=" + areaPid + ", areas=" + areas + "]";
	}


}