package com.zoubei.entity.other;

public class Jurisdict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_jurisdict.jur_id
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    private Integer jurId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_jurisdict.jur_name
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    private String jurName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_jurisdict.jur_id
     *
     * @return the value of tra_jurisdict.jur_id
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    public Integer getJurId() {
        return jurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_jurisdict.jur_id
     *
     * @param jurId the value for tra_jurisdict.jur_id
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    public void setJurId(Integer jurId) {
        this.jurId = jurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_jurisdict.jur_name
     *
     * @return the value of tra_jurisdict.jur_name
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    public String getJurName() {
        return jurName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_jurisdict.jur_name
     *
     * @param jurName the value for tra_jurisdict.jur_name
     *
     * @mbggenerated Sun Apr 15 15:19:43 CST 2018
     */
    public void setJurName(String jurName) {
        this.jurName = jurName;
    }
}