package com.zoubei.entity.other;

public class JurUrlRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_jur_url_rel.jur_id
     *
     * @mbggenerated Sun Apr 15 15:20:10 CST 2018
     */
    private Integer jurId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_jur_url_rel.url_id
     *
     * @mbggenerated Sun Apr 15 15:20:10 CST 2018
     */
    private Integer urlId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_jur_url_rel.jur_id
     *
     * @return the value of tra_jur_url_rel.jur_id
     *
     * @mbggenerated Sun Apr 15 15:20:10 CST 2018
     */
    public Integer getJurId() {
        return jurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_jur_url_rel.jur_id
     *
     * @param jurId the value for tra_jur_url_rel.jur_id
     *
     * @mbggenerated Sun Apr 15 15:20:10 CST 2018
     */
    public void setJurId(Integer jurId) {
        this.jurId = jurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_jur_url_rel.url_id
     *
     * @return the value of tra_jur_url_rel.url_id
     *
     * @mbggenerated Sun Apr 15 15:20:10 CST 2018
     */
    public Integer getUrlId() {
        return urlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_jur_url_rel.url_id
     *
     * @param urlId the value for tra_jur_url_rel.url_id
     *
     * @mbggenerated Sun Apr 15 15:20:10 CST 2018
     */
    public void setUrlId(Integer urlId) {
        this.urlId = urlId;
    }
}