package com.zoubei.entity.other;

public class Level {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_level.level_id
     *
     * @mbggenerated Sun Apr 15 15:21:28 CST 2018
     */
    private Integer levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_level.level_name
     *
     * @mbggenerated Sun Apr 15 15:21:28 CST 2018
     */
    private String levelName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_level.level_id
     *
     * @return the value of tra_level.level_id
     *
     * @mbggenerated Sun Apr 15 15:21:28 CST 2018
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_level.level_id
     *
     * @param levelId the value for tra_level.level_id
     *
     * @mbggenerated Sun Apr 15 15:21:28 CST 2018
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_level.level_name
     *
     * @return the value of tra_level.level_name
     *
     * @mbggenerated Sun Apr 15 15:21:28 CST 2018
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_level.level_name
     *
     * @param levelName the value for tra_level.level_name
     *
     * @mbggenerated Sun Apr 15 15:21:28 CST 2018
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }
}