package com.zoubei.entity.other;

public class SuperManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_supermanager.sup_id
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    private Integer supId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_supermanager.sup_nickname
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    private String supNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_supermanager.sup_password
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    private String supPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_supermanager.jur_id
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    private Integer jurId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_supermanager.sup_id
     *
     * @return the value of tra_supermanager.sup_id
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    public Integer getSupId() {
        return supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_supermanager.sup_id
     *
     * @param supId the value for tra_supermanager.sup_id
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    public void setSupId(Integer supId) {
        this.supId = supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_supermanager.sup_nickname
     *
     * @return the value of tra_supermanager.sup_nickname
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    public String getSupNickname() {
        return supNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_supermanager.sup_nickname
     *
     * @param supNickname the value for tra_supermanager.sup_nickname
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    public void setSupNickname(String supNickname) {
        this.supNickname = supNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_supermanager.sup_password
     *
     * @return the value of tra_supermanager.sup_password
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    public String getSupPassword() {
        return supPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_supermanager.sup_password
     *
     * @param supPassword the value for tra_supermanager.sup_password
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    public void setSupPassword(String supPassword) {
        this.supPassword = supPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_supermanager.jur_id
     *
     * @return the value of tra_supermanager.jur_id
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    public Integer getJurId() {
        return jurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_supermanager.jur_id
     *
     * @param jurId the value for tra_supermanager.jur_id
     *
     * @mbggenerated Sun Apr 15 15:19:25 CST 2018
     */
    public void setJurId(Integer jurId) {
        this.jurId = jurId;
    }
}