package com.zoubei.entity.other;

public class Url {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_url.url_id
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    private Integer urlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_url.url_name
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    private String urlName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_url.url_id
     *
     * @return the value of tra_url.url_id
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    public Integer getUrlId() {
        return urlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_url.url_id
     *
     * @param urlId the value for tra_url.url_id
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    public void setUrlId(Integer urlId) {
        this.urlId = urlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_url.url_name
     *
     * @return the value of tra_url.url_name
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    public String getUrlName() {
        return urlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_url.url_name
     *
     * @param urlName the value for tra_url.url_name
     *
     * @mbggenerated Sun Apr 15 15:19:53 CST 2018
     */
    public void setUrlName(String urlName) {
        this.urlName = urlName;
    }
}