package com.zoubei.entity.tourist;

import java.util.Date;

public class TouristAwardRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_award.tourist_id
     *
     * @mbggenerated Sun Apr 15 14:50:28 CST 2018
     */
    private Integer touristId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_award.award_name
     *
     * @mbggenerated Sun Apr 15 14:50:28 CST 2018
     */
    private String awardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_award.award_datetime
     *
     * @mbggenerated Sun Apr 15 14:50:28 CST 2018
     */
    private Date awardDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_award.tourist_id
     *
     * @return the value of tra_tourist_award.tourist_id
     *
     * @mbggenerated Sun Apr 15 14:50:28 CST 2018
     */
    public Integer getTouristId() {
        return touristId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_award.tourist_id
     *
     * @param touristId the value for tra_tourist_award.tourist_id
     *
     * @mbggenerated Sun Apr 15 14:50:28 CST 2018
     */
    public void setTouristId(Integer touristId) {
        this.touristId = touristId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_award.award_name
     *
     * @return the value of tra_tourist_award.award_name
     *
     * @mbggenerated Sun Apr 15 14:50:28 CST 2018
     */
    public String getAwardName() {
        return awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_award.award_name
     *
     * @param awardName the value for tra_tourist_award.award_name
     *
     * @mbggenerated Sun Apr 15 14:50:28 CST 2018
     */
    public void setAwardName(String awardName) {
        this.awardName = awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_award.award_datetime
     *
     * @return the value of tra_tourist_award.award_datetime
     *
     * @mbggenerated Sun Apr 15 14:50:28 CST 2018
     */
    public Date getAwardDatetime() {
        return awardDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_award.award_datetime
     *
     * @param awardDatetime the value for tra_tourist_award.award_datetime
     *
     * @mbggenerated Sun Apr 15 14:50:28 CST 2018
     */
    public void setAwardDatetime(Date awardDatetime) {
        this.awardDatetime = awardDatetime;
    }
}