package com.zoubei.entity.tourist;

public class TouristCatelCollecRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_cate_collec_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:17:19 CST 2018
     */
    private Integer touristId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_cate_collec_rel.cate_id
     *
     * @mbggenerated Sun Apr 15 15:17:19 CST 2018
     */
    private Integer cateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_cate_collec_rel.tourist_id
     *
     * @return the value of tra_tourist_cate_collec_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:17:19 CST 2018
     */
    public Integer getTouristId() {
        return touristId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_cate_collec_rel.tourist_id
     *
     * @param touristId the value for tra_tourist_cate_collec_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:17:19 CST 2018
     */
    public void setTouristId(Integer touristId) {
        this.touristId = touristId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_cate_collec_rel.cate_id
     *
     * @return the value of tra_tourist_cate_collec_rel.cate_id
     *
     * @mbggenerated Sun Apr 15 15:17:19 CST 2018
     */
    public Integer getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_cate_collec_rel.cate_id
     *
     * @param cateId the value for tra_tourist_cate_collec_rel.cate_id
     *
     * @mbggenerated Sun Apr 15 15:17:19 CST 2018
     */
    public void setCateId(Integer cateId) {
        this.cateId = cateId;
    }
}