package com.zoubei.entity.tourist;

import java.util.Date;
/**
 * 
 * @项目名称：maven_travel 酒店评论表
 *
 * @author ： YXM
 *
 * @date : 2018年4月28日 下午2:40:11
 */
public class TouristHotelEvaluateRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_hotel_evaluate_rel.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    private Integer appraiseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_hotel_evaluate_rel.thr_id
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    private Integer thrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_hotel_evaluate_rel.appraise_content
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    private String appraiseContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_hotel_evaluate_rel.appraise_date
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    private Date appraiseDate;
    //时间转换
    private String appraiseDates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_hotel_evaluate_rel.level_id
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    private Integer levelId;
    
    /*************************添加需求字段************************************/

    private Integer hotelId ;
    
    private String hotelHotelname ;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_hotel_evaluate_rel.appraise_id
     *
     * @return the value of tra_tourist_hotel_evaluate_rel.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    public Integer getAppraiseId() {
        return appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_hotel_evaluate_rel.appraise_id
     *
     * @param appraiseId the value for tra_tourist_hotel_evaluate_rel.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    public void setAppraiseId(Integer appraiseId) {
        this.appraiseId = appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_hotel_evaluate_rel.thr_id
     *
     * @return the value of tra_tourist_hotel_evaluate_rel.thr_id
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    public Integer getThrId() {
        return thrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_hotel_evaluate_rel.thr_id
     *
     * @param thrId the value for tra_tourist_hotel_evaluate_rel.thr_id
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    public void setThrId(Integer thrId) {
        this.thrId = thrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_hotel_evaluate_rel.appraise_content
     *
     * @return the value of tra_tourist_hotel_evaluate_rel.appraise_content
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    public String getAppraiseContent() {
        return appraiseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_hotel_evaluate_rel.appraise_content
     *
     * @param appraiseContent the value for tra_tourist_hotel_evaluate_rel.appraise_content
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    public void setAppraiseContent(String appraiseContent) {
        this.appraiseContent = appraiseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_hotel_evaluate_rel.appraise_date
     *
     * @return the value of tra_tourist_hotel_evaluate_rel.appraise_date
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    public Date getAppraiseDate() {
        return appraiseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_hotel_evaluate_rel.appraise_date
     *
     * @param appraiseDate the value for tra_tourist_hotel_evaluate_rel.appraise_date
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    public void setAppraiseDate(Date appraiseDate) {
        this.appraiseDate = appraiseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_hotel_evaluate_rel.level_id
     *
     * @return the value of tra_tourist_hotel_evaluate_rel.level_id
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_hotel_evaluate_rel.level_id
     *
     * @param levelId the value for tra_tourist_hotel_evaluate_rel.level_id
     *
     * @mbggenerated Sun Apr 15 15:17:45 CST 2018
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

	public String getAppraiseDates() {
		return appraiseDates;
	}

	public void setAppraiseDates(String appraiseDates) {
		this.appraiseDates = appraiseDates;
	}

	public Integer getHotelId() {
		return hotelId;
	}

	public void setHotelId(Integer hotelId) {
		this.hotelId = hotelId;
	}

	public String getHotelHotelname() {
		return hotelHotelname;
	}

	public void setHotelHotelname(String hotelHotelname) {
		this.hotelHotelname = hotelHotelname;
	}
}