package com.zoubei.entity.tourist;

public class TouristHotelCollecRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_hotel_collec_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:18:40 CST 2018
     */
    private Integer touristId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_hotel_collec_rel.hotel_id
     *
     * @mbggenerated Sun Apr 15 15:18:40 CST 2018
     */
    private Integer hotelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_hotel_collec_rel.tourist_id
     *
     * @return the value of tra_tourist_hotel_collec_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:18:40 CST 2018
     */
    public Integer getTouristId() {
        return touristId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_hotel_collec_rel.tourist_id
     *
     * @param touristId the value for tra_tourist_hotel_collec_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:18:40 CST 2018
     */
    public void setTouristId(Integer touristId) {
        this.touristId = touristId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_hotel_collec_rel.hotel_id
     *
     * @return the value of tra_tourist_hotel_collec_rel.hotel_id
     *
     * @mbggenerated Sun Apr 15 15:18:40 CST 2018
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_hotel_collec_rel.hotel_id
     *
     * @param hotelId the value for tra_tourist_hotel_collec_rel.hotel_id
     *
     * @mbggenerated Sun Apr 15 15:18:40 CST 2018
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }
}