package com.zoubei.entity.tourist;

import java.util.Date;
/**
 * 
 * @项目名称：maven_travel  景点评论
 *
 * @author ： YXM
 *
 * @date : 2018年4月28日 下午5:22:48
 */
public class TouristSceneAppraise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_appraise.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    private Integer appraiseId;
    
    //景点名称
    private String sceneName ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_appraise.order_id
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_appraise.appraise_content
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    private String appraiseContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_appraise.appraise_date
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    private Date appraiseDate;
    
    //时间
    private String appraiseDates ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_scene_appraise.level_id
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    private Integer levelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_appraise.appraise_id
     *
     * @return the value of tra_scene_appraise.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    public Integer getAppraiseId() {
        return appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_appraise.appraise_id
     *
     * @param appraiseId the value for tra_scene_appraise.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    public void setAppraiseId(Integer appraiseId) {
        this.appraiseId = appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_appraise.order_id
     *
     * @return the value of tra_scene_appraise.order_id
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_appraise.order_id
     *
     * @param orderId the value for tra_scene_appraise.order_id
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_appraise.appraise_content
     *
     * @return the value of tra_scene_appraise.appraise_content
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    public String getAppraiseContent() {
        return appraiseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_appraise.appraise_content
     *
     * @param appraiseContent the value for tra_scene_appraise.appraise_content
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    public void setAppraiseContent(String appraiseContent) {
        this.appraiseContent = appraiseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_appraise.appraise_date
     *
     * @return the value of tra_scene_appraise.appraise_date
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    public Date getAppraiseDate() {
        return appraiseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_appraise.appraise_date
     *
     * @param appraiseDate the value for tra_scene_appraise.appraise_date
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    public void setAppraiseDate(Date appraiseDate) {
        this.appraiseDate = appraiseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_scene_appraise.level_id
     *
     * @return the value of tra_scene_appraise.level_id
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_scene_appraise.level_id
     *
     * @param levelId the value for tra_scene_appraise.level_id
     *
     * @mbggenerated Sun Apr 15 15:08:21 CST 2018
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

	public String getSceneName() {
		return sceneName;
	}

	public void setSceneName(String sceneName) {
		this.sceneName = sceneName;
	}

	public String getAppraiseDates() {
		return appraiseDates;
	}

	public void setAppraiseDates(String appraiseDates) {
		this.appraiseDates = appraiseDates;
	}

}