package com.zoubei.entity.tourist;

public class TouristSceneCollecRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_scene_collec_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:06:01 CST 2018
     */
    private Integer touristId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_tourist_scene_collec_rel.scene_id
     *
     * @mbggenerated Sun Apr 15 15:06:01 CST 2018
     */
    private Integer sceneId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_scene_collec_rel.tourist_id
     *
     * @return the value of tra_tourist_scene_collec_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:06:01 CST 2018
     */
    public Integer getTouristId() {
        return touristId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_scene_collec_rel.tourist_id
     *
     * @param touristId the value for tra_tourist_scene_collec_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:06:01 CST 2018
     */
    public void setTouristId(Integer touristId) {
        this.touristId = touristId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_tourist_scene_collec_rel.scene_id
     *
     * @return the value of tra_tourist_scene_collec_rel.scene_id
     *
     * @mbggenerated Sun Apr 15 15:06:01 CST 2018
     */
    public Integer getSceneId() {
        return sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_tourist_scene_collec_rel.scene_id
     *
     * @param sceneId the value for tra_tourist_scene_collec_rel.scene_id
     *
     * @mbggenerated Sun Apr 15 15:06:01 CST 2018
     */
    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }
}