package com.zoubei.entity.tourist;

import java.util.Date;

public class TouristCatelRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_touris_catel_rel.order_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_touris_catel_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    private Integer touristId;
    private String touristNickname ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_touris_catel_rel.food_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    private Integer foodId;
    private String foodName ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_touris_catel_rel.order_date
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    private Date orderDate;
    private String orderDates;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_touris_catel_rel.order_num
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_touris_catel_rel.status_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    private Integer statusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_touris_catel_rel.order_id
     *
     * @return the value of tra_touris_catel_rel.order_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_touris_catel_rel.order_id
     *
     * @param orderId the value for tra_touris_catel_rel.order_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_touris_catel_rel.tourist_id
     *
     * @return the value of tra_touris_catel_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public Integer getTouristId() {
        return touristId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_touris_catel_rel.tourist_id
     *
     * @param touristId the value for tra_touris_catel_rel.tourist_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public void setTouristId(Integer touristId) {
        this.touristId = touristId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_touris_catel_rel.food_id
     *
     * @return the value of tra_touris_catel_rel.food_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public Integer getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_touris_catel_rel.food_id
     *
     * @param foodId the value for tra_touris_catel_rel.food_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_touris_catel_rel.order_date
     *
     * @return the value of tra_touris_catel_rel.order_date
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_touris_catel_rel.order_date
     *
     * @param orderDate the value for tra_touris_catel_rel.order_date
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_touris_catel_rel.order_num
     *
     * @return the value of tra_touris_catel_rel.order_num
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_touris_catel_rel.order_num
     *
     * @param orderNum the value for tra_touris_catel_rel.order_num
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_touris_catel_rel.status_id
     *
     * @return the value of tra_touris_catel_rel.status_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_touris_catel_rel.status_id
     *
     * @param statusId the value for tra_touris_catel_rel.status_id
     *
     * @mbggenerated Sun Apr 15 15:16:16 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

	public String getTouristNickname() {
		return touristNickname;
	}

	public void setTouristNickname(String touristNickname) {
		this.touristNickname = touristNickname;
	}

	public String getFoodName() {
		return foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	public String getOrderDates() {
		return orderDates;
	}

	public void setOrderDates(String orderDates) {
		this.orderDates = orderDates;
	}
}