package com.zoubei.entity.tourist;

import java.util.Date;
/**
 * 
 * @项目名称：maven_travel 美食评论表
 *
 * @author ： YXM
 *
 * @date : 2018年4月28日 下午1:17:16
 */
public class TouristCatelEvaluateRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_touris_catel_evaluate.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    private Integer appraiseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_touris_catel_evaluate.order_id
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_touris_catel_evaluate.appraise_content
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    private String appraiseContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_touris_catel_evaluate.appraise_date
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    private Date appraiseDate;
    private String  appraiseDates ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_touris_catel_evaluate.level_id
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    private Integer levelId;
    
    
    /***********************新增关联查询美食评论数据*********************************/

    private Integer cateId ;
    
    private String cateShopname ;
    
    private Integer foodId ;
    
    private String foodName ;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_touris_catel_evaluate.appraise_id
     *
     * @return the value of tra_touris_catel_evaluate.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    public Integer getAppraiseId() {
        return appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_touris_catel_evaluate.appraise_id
     *
     * @param appraiseId the value for tra_touris_catel_evaluate.appraise_id
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    public void setAppraiseId(Integer appraiseId) {
        this.appraiseId = appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_touris_catel_evaluate.order_id
     *
     * @return the value of tra_touris_catel_evaluate.order_id
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_touris_catel_evaluate.order_id
     *
     * @param orderId the value for tra_touris_catel_evaluate.order_id
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_touris_catel_evaluate.appraise_content
     *
     * @return the value of tra_touris_catel_evaluate.appraise_content
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    public String getAppraiseContent() {
        return appraiseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_touris_catel_evaluate.appraise_content
     *
     * @param appraiseContent the value for tra_touris_catel_evaluate.appraise_content
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    public void setAppraiseContent(String appraiseContent) {
        this.appraiseContent = appraiseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_touris_catel_evaluate.appraise_date
     *
     * @return the value of tra_touris_catel_evaluate.appraise_date
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    public Date getAppraiseDate() {
        return appraiseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_touris_catel_evaluate.appraise_date
     *
     * @param appraiseDate the value for tra_touris_catel_evaluate.appraise_date
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    public void setAppraiseDate(Date appraiseDate) {
        this.appraiseDate = appraiseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_touris_catel_evaluate.level_id
     *
     * @return the value of tra_touris_catel_evaluate.level_id
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_touris_catel_evaluate.level_id
     *
     * @param levelId the value for tra_touris_catel_evaluate.level_id
     *
     * @mbggenerated Sun Apr 15 15:16:00 CST 2018
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

	public Integer getCateId() {
		return cateId;
	}

	public void setCateId(Integer cateId) {
		this.cateId = cateId;
	}

	public String getCateShopname() {
		return cateShopname;
	}

	public void setCateShopname(String cateShopname) {
		this.cateShopname = cateShopname;
	}

	public Integer getFoodId() {
		return foodId;
	}

	public void setFoodId(Integer foodId) {
		this.foodId = foodId;
	}

	public String getFoodName() {
		return foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	public String getAppraiseDates() {
		return appraiseDates;
	}

	public void setAppraiseDates(String appraiseDates) {
		this.appraiseDates = appraiseDates;
	}
    
}