package com.zoubei.mapper.hotel;

import java.util.List;

import com.zoubei.entity.hotel.Hotel;

public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    int deleteByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    Hotel selectByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    int updateByPrimaryKeySelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel
     *
     * @mbggenerated Sun Apr 15 14:55:18 CST 2018
     */
    int updateByPrimaryKey(Hotel record);

    //根据景点区域id 查询该区域酒店 排行优先推荐销量高的酒店推荐 order by
	List<Hotel> selectHotelBySceneAreaId(Integer areaId);

	// 查询景点所在区域的酒店list集合
	List<Hotel> selectHotelBySceneId(Integer sceneId);
	

	//查询不同城市地区的酒店
	List<Hotel> selectHotelList(Integer areaId);

	//添加酒店并且返回主键
	void insertHotelByReturnKey(Hotel hotel);

	Hotel selectHotelEchoByHotelId(Integer hotelId);

	List<Hotel> selectHotelGroupList(Integer hgpId);

	List<Hotel> selectHotelByAreaId(int areaId);

}