package com.zoubei.mapper.hotel;

import java.util.List;

import com.zoubei.entity.hotel.HotelPrice;

public interface HotelPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    int deleteByPrimaryKey(Integer priceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    int insert(HotelPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    int insertSelective(HotelPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    HotelPrice selectByPrimaryKey(Integer priceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    int updateByPrimaryKeySelective(HotelPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price
     *
     * @mbggenerated Sun Apr 15 15:11:14 CST 2018
     */
    int updateByPrimaryKey(HotelPrice record);

	List<HotelPrice> selectHotelPriceList();
}