package com.zoubei.mapper.hotel;

import com.zoubei.entity.hotel.HotelPriceRel;

public interface HotelPriceRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price_rel
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    int deleteByPrimaryKey(Integer hprId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price_rel
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    int insert(HotelPriceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price_rel
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    int insertSelective(HotelPriceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price_rel
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    HotelPriceRel selectByPrimaryKey(Integer hprId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price_rel
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    int updateByPrimaryKeySelective(HotelPriceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_price_rel
     *
     * @mbggenerated Sun Apr 15 15:10:50 CST 2018
     */
    int updateByPrimaryKey(HotelPriceRel record);

    //通过酒店Id获得价格类型中间表
	HotelPriceRel selectHotelAreaByHotelId(Integer hotelId);

	void deleteHotelPriceRelByhotelId(Integer hotelId);
}