package com.zoubei.mapper.hotel;

import java.util.List;

import com.zoubei.entity.hotel.HotelType;

public interface HotelTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_type
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    int deleteByPrimaryKey(Integer typeiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_type
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    int insert(HotelType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_type
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    int insertSelective(HotelType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_type
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    HotelType selectByPrimaryKey(Integer typeiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_type
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    int updateByPrimaryKeySelective(HotelType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_type
     *
     * @mbggenerated Sun Apr 15 15:11:38 CST 2018
     */
    int updateByPrimaryKey(HotelType record);

	List<HotelType> selectHotelTypeList();
}