package com.zoubei.mapper.hotel;

import com.zoubei.entity.hotel.HotelGroupRel;

public interface HotelGroupRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_group_rel
     *
     * @mbggenerated Sun Apr 15 15:10:19 CST 2018
     */
    int insert(HotelGroupRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_hotel_group_rel
     *
     * @mbggenerated Sun Apr 15 15:10:19 CST 2018
     */
    int insertSelective(HotelGroupRel record);
}