package com.zoubei.entity.cate;

public class CateGroupRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate_group_rel.cgp_id
     *
     * @mbggenerated Sun Apr 15 15:04:41 CST 2018
     */
    private Integer cgpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate_group_rel.cate_id
     *
     * @mbggenerated Sun Apr 15 15:04:41 CST 2018
     */
    private Integer cateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate_group_rel.cgp_id
     *
     * @return the value of tra_cate_group_rel.cgp_id
     *
     * @mbggenerated Sun Apr 15 15:04:41 CST 2018
     */
    public Integer getCgpId() {
        return cgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate_group_rel.cgp_id
     *
     * @param cgpId the value for tra_cate_group_rel.cgp_id
     *
     * @mbggenerated Sun Apr 15 15:04:41 CST 2018
     */
    public void setCgpId(Integer cgpId) {
        this.cgpId = cgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate_group_rel.cate_id
     *
     * @return the value of tra_cate_group_rel.cate_id
     *
     * @mbggenerated Sun Apr 15 15:04:41 CST 2018
     */
    public Integer getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate_group_rel.cate_id
     *
     * @param cateId the value for tra_cate_group_rel.cate_id
     *
     * @mbggenerated Sun Apr 15 15:04:41 CST 2018
     */
    public void setCateId(Integer cateId) {
        this.cateId = cateId;
    }
}