package com.zoubei.entity.cate;

public class CateGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate_group.cgp_id
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    private Integer cgpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate_group.cgp_nickname
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    private String cgpNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate_group.cgp_password
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    private String cgpPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate_group.cgp_realname
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    private String cgpRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate_group.jur_id
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    private Integer jurId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate_group.status_id
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    private Integer statusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate_group.cgp_id
     *
     * @return the value of tra_cate_group.cgp_id
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public Integer getCgpId() {
        return cgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate_group.cgp_id
     *
     * @param cgpId the value for tra_cate_group.cgp_id
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public void setCgpId(Integer cgpId) {
        this.cgpId = cgpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate_group.cgp_nickname
     *
     * @return the value of tra_cate_group.cgp_nickname
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public String getCgpNickname() {
        return cgpNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate_group.cgp_nickname
     *
     * @param cgpNickname the value for tra_cate_group.cgp_nickname
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public void setCgpNickname(String cgpNickname) {
        this.cgpNickname = cgpNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate_group.cgp_password
     *
     * @return the value of tra_cate_group.cgp_password
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public String getCgpPassword() {
        return cgpPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate_group.cgp_password
     *
     * @param cgpPassword the value for tra_cate_group.cgp_password
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public void setCgpPassword(String cgpPassword) {
        this.cgpPassword = cgpPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate_group.cgp_realname
     *
     * @return the value of tra_cate_group.cgp_realname
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public String getCgpRealname() {
        return cgpRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate_group.cgp_realname
     *
     * @param cgpRealname the value for tra_cate_group.cgp_realname
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public void setCgpRealname(String cgpRealname) {
        this.cgpRealname = cgpRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate_group.jur_id
     *
     * @return the value of tra_cate_group.jur_id
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public Integer getJurId() {
        return jurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate_group.jur_id
     *
     * @param jurId the value for tra_cate_group.jur_id
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public void setJurId(Integer jurId) {
        this.jurId = jurId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate_group.status_id
     *
     * @return the value of tra_cate_group.status_id
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate_group.status_id
     *
     * @param statusId the value for tra_cate_group.status_id
     *
     * @mbggenerated Sun Apr 15 15:12:17 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
}