package com.zoubei.entity.cate;

public class Cate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate.cate_id
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    private Integer cateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate.cate_shopname
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    private String cateShopname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate.area_id
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate.cate_address
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    private String cateAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate.level_id
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    private Integer levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate.cate_sales
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    private Integer cateSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate.cate_message
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    private String cateMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate.cate_tel
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    private String cateTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_cate.cate_logo
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    private String cateLogo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate.cate_id
     *
     * @return the value of tra_cate.cate_id
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public Integer getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate.cate_id
     *
     * @param cateId the value for tra_cate.cate_id
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public void setCateId(Integer cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate.cate_shopname
     *
     * @return the value of tra_cate.cate_shopname
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public String getCateShopname() {
        return cateShopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate.cate_shopname
     *
     * @param cateShopname the value for tra_cate.cate_shopname
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public void setCateShopname(String cateShopname) {
        this.cateShopname = cateShopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate.area_id
     *
     * @return the value of tra_cate.area_id
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate.area_id
     *
     * @param areaId the value for tra_cate.area_id
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate.cate_address
     *
     * @return the value of tra_cate.cate_address
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public String getCateAddress() {
        return cateAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate.cate_address
     *
     * @param cateAddress the value for tra_cate.cate_address
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public void setCateAddress(String cateAddress) {
        this.cateAddress = cateAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate.level_id
     *
     * @return the value of tra_cate.level_id
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate.level_id
     *
     * @param levelId the value for tra_cate.level_id
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate.cate_sales
     *
     * @return the value of tra_cate.cate_sales
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public Integer getCateSales() {
        return cateSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate.cate_sales
     *
     * @param cateSales the value for tra_cate.cate_sales
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public void setCateSales(Integer cateSales) {
        this.cateSales = cateSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate.cate_message
     *
     * @return the value of tra_cate.cate_message
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public String getCateMessage() {
        return cateMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate.cate_message
     *
     * @param cateMessage the value for tra_cate.cate_message
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public void setCateMessage(String cateMessage) {
        this.cateMessage = cateMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate.cate_tel
     *
     * @return the value of tra_cate.cate_tel
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public String getCateTel() {
        return cateTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate.cate_tel
     *
     * @param cateTel the value for tra_cate.cate_tel
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public void setCateTel(String cateTel) {
        this.cateTel = cateTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_cate.cate_logo
     *
     * @return the value of tra_cate.cate_logo
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public String getCateLogo() {
        return cateLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_cate.cate_logo
     *
     * @param cateLogo the value for tra_cate.cate_logo
     *
     * @mbggenerated Sun Apr 15 15:04:11 CST 2018
     */
    public void setCateLogo(String cateLogo) {
        this.cateLogo = cateLogo;
    }
}