package com.zoubei.entity.cate;

public class FoodsImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_foods_img.food_id
     *
     * @mbggenerated Thu Apr 26 19:15:31 CST 2018
     */
    private Integer foodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_foods_img.food_img
     *
     * @mbggenerated Thu Apr 26 19:15:31 CST 2018
     */
    private String foodImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_foods_img.food_id
     *
     * @return the value of tra_foods_img.food_id
     *
     * @mbggenerated Thu Apr 26 19:15:31 CST 2018
     */
    public Integer getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_foods_img.food_id
     *
     * @param foodId the value for tra_foods_img.food_id
     *
     * @mbggenerated Thu Apr 26 19:15:31 CST 2018
     */
    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_foods_img.food_img
     *
     * @return the value of tra_foods_img.food_img
     *
     * @mbggenerated Thu Apr 26 19:15:31 CST 2018
     */
    public String getFoodImg() {
        return foodImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_foods_img.food_img
     *
     * @param foodImg the value for tra_foods_img.food_img
     *
     * @mbggenerated Thu Apr 26 19:15:31 CST 2018
     */
    public void setFoodImg(String foodImg) {
        this.foodImg = foodImg;
    }
}